"""empty message

Revision ID: 14177b0198ba
Revises: fc853819b043
Create Date: 2024-10-19 19:31:49.116695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14177b0198ba'
down_revision = 'fc853819b043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_activated_account', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_activated_account')

    # ### end Alembic commands ###
