"""empty message

Revision ID: 213c41db52f6
Revises: ccbed58b46eb
Create Date: 2024-10-18 16:08:12.987519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213c41db52f6'
down_revision = 'ccbed58b46eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_key', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('secret_key')

    # ### end Alembic commands ###
